blog/api/urls.py
from django.urls import path
from blog.api.views import(
	api_detail_blog_view,
	api_update_blog_view,
	api_delete_blog_view,
	api_create_blog_view,

	ApiBlogListView
)

app_name = 'blog'

urlpatterns = [
	path('<slug>/', api_detail_blog_view, name="detail"),
	path('<slug>/update', api_update_blog_view, name="update"),
	path('<slug>/delete', api_delete_blog_view, name="delete"),
	path('create', api_create_blog_view, name="create"),
	path('list', ApiBlogListView.as_view(), name="list"),
]

blog/urls.py
from unicodedata import name
from django.urls import path

from blog.views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    edit_commnet_view,
    delete_commnet_view,
    add_like,
    add_dislike,
    delete_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),
    path('<slug>/edit/delete-blog', delete_blog_view, name="delete-blog"),
    # fix path
    path('<slug>/<int:pk>/comment/edit', edit_commnet_view, name="comment-edit"),
    path('<slug>/comment/<int:pk>/delete', delete_commnet_view, name="comment-delete"),
    path('<slug>/<int:pk>/like', add_like, name="like"),
    path('<slug>/<int:pk>/dislike', add_dislike, name="dislike"),
]

mysite/urls.py
from unicodedata import name
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
#my views
from personal.views import (
    
    home_screen_view,
)
    
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)
 
    



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('register/', registration_view, name="register"),  
    path('logout/', logout_view, name="logout"),  
    path('login/', login_view, name="login"),  
    path('blog/', include('blog.urls', 'blog')),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),  
    path('account/', account_view, name="account"),

    # path('__debug__/', include('debug_toolbar.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    # to su django source code views for  password reset  (ne trebamo svoje) i svi urlovi za password reset po django dokumentaciji
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),  
]
#postava url i roota za static i media  
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/forms.py
from django import forms

from blog.models import BlogPost, Comment

class CreateBlogPostForm(forms.ModelForm):
    
    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']

class UpdateBlogPostForm(forms.ModelForm):
    
    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']
    
    def save(self, commit=True):
        blog_post = self.instance
        blog_post.title = self.cleaned_data['title']
        blog_post.body = self.cleaned_data['body']

        if self.cleaned_data['image']:
            blog_post.image = self.cleaned_data['image']
        
        if commit:
            blog_post.save()
        return blog_post

class CommentForm(forms.ModelForm):
    comment = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={'rows': '3', 'style': 'width: 99% !important; resize: vertical !important;',
                   'placeholder': 'Comment here...'}
        ))
    
    class Meta:
        model = Comment
        fields = ['comment']

class EditCommentForm(forms.ModelForm):
    comment = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={'rows': '3', 'max-cols':'75',
                   'placeholder': 'Comment here...'}
        ))
    
    class Meta:
        model = Comment
        fields = ['comment']

blog/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import ListAPIView
from rest_framework.filters import SearchFilter, OrderingFilter

from account.models import Account
from blog.models import BlogPost
from blog.api.serializers import BlogPostSerializer

SUCCESS = 'success'
ERROR = 'error'
DELETE_SUCCESS = 'deleted'
UPDATE_SUCCESS = 'updated'


# Url: https://<your-domain>/api/blog/<slug>/
# Headers: Authorization: Token <token>
@api_view(['GET', ])
@permission_classes((IsAuthenticated, ))
def api_detail_blog_view(request, slug):

	try:
		blog_post = BlogPost.objects.get(slug=slug)
	except BlogPost.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	if request.method == 'GET':
		serializer = BlogPostSerializer(blog_post)
		return Response(serializer.data)



# Url: https://<your-domain>/api/blog/<slug>/update
# Headers: Authorization: Token <token>
@api_view(['PUT',])
@permission_classes((IsAuthenticated, ))
def api_update_blog_view(request, slug):

	try:
		blog_post = BlogPost.objects.get(slug=slug)
	except BlogPost.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	user = request.user
	if blog_post.author != user:
		return Response({'response':"You don't have permission to edit that."}) 
		
	if request.method == 'PUT':
		serializer = BlogPostSerializer(blog_post, data=request.data)
		data = {}
		if serializer.is_valid():
			serializer.save()
			data['response'] = UPDATE_SUCCESS
			return Response(data=data)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



# Url: https://<your-domain>/api/blog/<slug>/delete
# Headers: Authorization: Token <token>
@api_view(['DELETE',])
@permission_classes((IsAuthenticated, ))
def api_delete_blog_view(request, slug):

	try:
		blog_post = BlogPost.objects.get(slug=slug)
	except BlogPost.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	user = request.user
	if blog_post.author != user:
		return Response({'response':"You don't have permission to delete that."}) 

	if request.method == 'DELETE':
		operation = blog_post.delete()
		data = {}
		if operation:
			data['response'] = DELETE_SUCCESS
		return Response(data=data)



# Url: https://<your-domain>/api/blog/create
# Headers: Authorization: Token <token>
@api_view(['POST'])
@permission_classes((IsAuthenticated, ))
def api_create_blog_view(request):

	blog_post = BlogPost(author=request.user)

	if request.method == 'POST':
		serializer = BlogPostSerializer(blog_post, data=request.data)
		data = {}
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



# Url: 
#		1) list: https://<your-domain>/api/blog/list
#		2) pagination: http://<your-domain>/api/blog/list?page=2
#		3) search: http://<your-domain>/api/blog/list?search=mitch
#		4) ordering: http://<your-domain>/api/blog/list?ordering=-date_updated
#		4) search + pagination + ordering: <your-domain>/api/blog/list?search=mitch&page=2&ordering=-date_updated
# Headers: Authorization: Token <token>
class ApiBlogListView(ListAPIView):
	queryset = BlogPost.objects.all()
	serializer_class = BlogPostSerializer
	authentication_classes = (TokenAuthentication,)
	permission_classes = (IsAuthenticated,)
	pagination_class = PageNumberPagination
	filter_backends = (SearchFilter, OrderingFilter)
	search_fields = ('title', 'body', 'author__username')

blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Q

from blog.forms import CreateBlogPostForm, UpdateBlogPostForm, CommentForm, EditCommentForm
from account.models import Account
from blog.models import BlogPost, Comment
from django.http import HttpResponse
from django.template import loader
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse

def create_blog_view(request):

    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()
        return redirect("home")
    context['form'] = form
    return render(request, "blog/create_blog.html", context)

def detail_blog_view(request, slug):

    context = {}
    user = request.user
    blog_post = get_object_or_404(BlogPost, slug=slug)
    
    if request.POST:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            obj = comment_form.save(commit=False)
            author = Account.objects.filter(email=user.email).first()
            obj.author = author
            obj.post = blog_post 
            obj.save()
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()
    
    comments = Comment.objects.filter(post=blog_post).order_by('-created_on')
    page = request.GET.get('page')
    results_per_page = 5
    paginator = Paginator(comments, results_per_page)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)
    
    
    context['blog_post'] = blog_post
    context['comment_form'] = comment_form
    context['comments'] = comments

    return render(request, 'blog/detail_blog.html', context)

def edit_blog_view(request, slug):

    context = {}
    user = request.user

    if not user.is_authenticated:
        return redirect("must_authenticate.html")
    
    
    blog_post = get_object_or_404(BlogPost, slug=slug)

    if blog_post.author != user:
        return HttpResponse("You are not the author of this post.")

    if request.POST:
        form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance = blog_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Updated"
            blog_post = obj
    form = UpdateBlogPostForm(
        initial={
            "title": blog_post.title,
            "body": blog_post.body,
            "image": blog_post.image,
        }
    )

    context['form'] = form
    context['slug'] = slug

    return render(request, 'blog/edit_blog.html', context)

def delete_blog_view(request, slug):
    context = {}
    user = request.user

    if not user.is_authenticated:
        return redirect("must_authenticate.html")
    
    
    blog_post = get_object_or_404(BlogPost, slug=slug)

    if blog_post.author != user:
        return HttpResponse("You are not the author of this post.")
    
    if request.method == 'GET':
        context['slug'] = slug
        return render(request, 'blog/delete_blog.html', context)
    
    if request.POST:
        blog_post.delete()

        return redirect('home')
    
   
    blog_post.delete()
    return redirect("home")

def get_blog_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        posts = BlogPost.objects.filter(
            Q(title__icontains = q) | #q serach
            Q(body__icontains = q)
        ).distinct() #gives unique posts in that list

        for post in posts:
            queryset.append(post)
    
    return list(set(queryset))

def edit_commnet_view(request, slug, pk):

    context = {}
    user = request.user

    if not user.is_authenticated:
        return redirect("must_authenticate.html")
    
    comment = Comment.objects.filter(pk=pk)[0]

    if comment.author != user:
        return HttpResponse("You are not the author of this comment.")

    comment_form = CommentForm()
    if request.method == 'GET':
        comment_form = CommentForm(
            initial={
            "comment": comment.comment,
        }
        )
        context['comment_form'] = comment_form
        context['slug'] = slug
        return render(request, 'blog/edit_comment.html', context)
    
    if request.POST:
        comment_form = CommentForm(request.POST or None, request.FILES or None, instance = comment)
        if comment_form.is_valid():
            obj = comment_form.save(commit=False)
            obj.save()
            
    next = request.POST.get('next', '/')
    return redirect(next)

def delete_commnet_view(request, slug, pk):

    context = {}
    user = request.user
    
    if not user.is_authenticated:
        return redirect("must_authenticate.html")
    
    
    comment = Comment.objects.filter(pk=pk)[0]

    if comment.author != user:
        return HttpResponse("You are not the author of this comment.")

    if request.method == 'GET':
        context['slug'] = slug
        return render(request, 'blog/delete_comment.html', context)
    
    if request.POST:
        comment.delete()
        next = request.POST.get('next', '/')

        return redirect(next)

def add_like(request, slug, pk):

    if not request.user.is_authenticated:
        return redirect('must_authenticate')

    if request.POST:
        post = BlogPost.objects.get(pk=pk)

        is_dislike = False

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if is_dislike:
            post.dislikes.remove(request.user)

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if not is_like:
            post.likes.add(request.user)

        if is_like:
            post.likes.remove(request.user)

        next = request.POST.get('next', '/')
        return redirect(next)

def add_dislike(request, slug, pk):

    if not request.user.is_authenticated:
        return redirect('must_authenticate')

    if request.POST:
        post = BlogPost.objects.get(pk=pk)

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if is_like:
            post.likes.remove(request.user)

        is_dislike = False

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if not is_dislike:
            post.dislikes.add(request.user)

        if is_dislike:
            post.dislikes.remove(request.user)

        next = request.POST.get('next', '/')
        return redirect(next)


#

blog/templates/blog/snippets/blog_post_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
    <nav aria-label="Page navigation">
    <ul class="pagination pg-grey justify-content-center">
        {% if blog_posts.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.previous_page_number }}">&laquo; Previous</a>
            </li>
        {% endif %}
    
        {% for i in blog_posts.paginator.page_range %}
            {% if blog_posts.number == i %}
                <li class="page-item active"><a class="page-link">{{ i }}</a></li>
            {% else %}
                <li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        
        {% if blog_posts.has_next %}
            <li class="page-item">
              <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.next_page_number }}">Next</a>
            </li>
            <li class="page-item">
              <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.paginator.num_pages }}">Last &raquo;</a>
            </li>
        {% endif %}
    </ul>
    </nav>
    </div>
    <!-- end pagination-->

blog/templates/blog/snippets/blog_post_snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;
        width: 100%;
	}
</style>

{% if blog_post %}
<div class="container">
	<div class="row">
		<!-- Blog Post -->
		<div class="card m-auto">
			<a href="{% url 'blog:detail' post.slug %}">
				<img class="card-img-top" src="{{blog_post.image.url}}">
			</a>
			<div class="card-body mt-2 mb-2">
				<a href="{% url 'blog:detail' post.slug %}">
					<h2 class="card-title">{{blog_post.title}}</h2>
				</a>
				<p class="card-text">{{blog_post.body|safe|truncatechars:250}}</p> <!--ovaj "safe" treba maknut u produkciji omogucava koristenje htmla-->
				{% if blog_post.author == request.user %}
					<a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Update</a>
				{% endif %}
			</div>
			{% include 'blog/snippets/like_dislike.html' %}
			<div class="card-footer text-muted">
			  Updated on {{blog_post.date_updated}} by {{blog_post.author}}
			</div>
		</div>
	</div>
</div>

{% else %}

<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title">No results</h2>
				<p class="card-text">There were no results matching the search: "{{query}}"</p>
			</div>
		</div>
	</div>
</div>

{% endif %}

blog/templates/blog/snippets/comment_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
    <nav aria-label="Page navigation">
    <ul class="pagination pg-grey justify-content-center">
        {% if comments.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ comments.previous_page_number }}">&laquo; Previous</a>
            </li>
        {% endif %}
    
        {% for i in comments.paginator.page_range %}
            {% if comments.number == i %}
                <li class="page-item active"><a class="page-link">{{ i }}</a></li>
            {% else %}
                <li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        
        {% if comments.has_next %}
            <li class="page-item">
              <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ comments.next_page_number }}">Next</a>
            </li>
            <li class="page-item">
              <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ comments.paginator.num_pages }}">Last &raquo;</a>
            </li>
        {% endif %}
    </ul>
    </nav>
    </div>
    <!-- end pagination-->

blog/templates/blog/snippets/comments.html
{% for comment in comments %}
		
			
				<p>
					<strong>{{comment.author.username}}</strong><small class="text-muted mb-1"> {{ comment.created_on }}</small>
					{% if request.user == comment.author %}
					<a href="{% url 'blog:comment-edit' blog_post.slug comment.pk %}?next={{ request.path|urlencode }}" style="color: #333;"><i class="fa fa-edit"></i></a>
					<a href="{% url 'blog:comment-delete' blog_post.slug comment.pk %}?next={{ request.path|urlencode }}" style="color: #333;"><i class="fa fa-trash"></i></a>
					{% endif %}
				</p>
				
				<p >{{comment.comment}}</p>
				{% if comment.updated_at %}
				<p><small class="text-muted mb-1"> Edited {{ comment.updated_at }}</small></p>
				{% endif %}
				<hr>
			
			
{% endfor %}

blog/templates/blog/snippets/like_dislike.html
    <form method="POST" action="{% url 'blog:like' post.slug post.pk %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.path }}">
        <button style="background-color: transparent; border: none; box-shadow: none;" type="submit">
            <i class="fa fa-thumbs-up" style="color: blue"> <span>{{ post.likes.all.count }}</span></i>
        </button>
    </form>

    <form method="POST" action="{% url 'blog:dislike' post.slug post.pk %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.path }}">
        <button style="background-color: transparent; border: none; box-shadow: none;" type="submit">
            <i class="fa fa-thumbs-down" style="color: red"> <span>{{ post.dislikes.all.count }}</span></i>
        </button>
    </form>