blog/api/urls.py
from django.urls import path
from blog.api.views import(
	api_detail_blog_view,
	api_update_blog_view,
	api_delete_blog_view,
	api_create_blog_view,

	ApiBlogListView
)

app_name = 'blog'

urlpatterns = [
	path('<slug>/', api_detail_blog_view, name="detail"),
	path('<slug>/update', api_update_blog_view, name="update"),
	path('<slug>/delete', api_delete_blog_view, name="delete"),
	path('create', api_create_blog_view, name="create"),
	path('list', ApiBlogListView.as_view(), name="list"),
]

blog/urls.py
from unicodedata import name
from django.urls import path

from blog.views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    edit_commnet_view,
    delete_commnet_view,
    add_like,
    add_dislike,
    delete_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),
    path('<slug>/edit/delete-blog', delete_blog_view, name="delete-blog"),
    # fix path
    path('<slug>/<int:pk>/comment/edit', edit_commnet_view, name="comment-edit"),
    path('<slug>/comment/<int:pk>/delete', delete_commnet_view, name="comment-delete"),
    path('<slug>/<int:pk>/like', add_like, name="like"),
    path('<slug>/<int:pk>/dislike', add_dislike, name="dislike"),
]

mysite/urls.py
from unicodedata import name
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
#my views
from personal.views import (
    
    home_screen_view,
)
    
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)
 
    



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('register/', registration_view, name="register"),  
    path('logout/', logout_view, name="logout"),  
    path('login/', login_view, name="login"),  
    path('blog/', include('blog.urls', 'blog')),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),  
    path('account/', account_view, name="account"),

    # path('__debug__/', include('debug_toolbar.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    # to su django source code views for  password reset  (ne trebamo svoje) i svi urlovi za password reset po django dokumentaciji
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),  
]
#postava url i roota za static i media  
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from django.db.models.signals import post_delete, pre_save
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver
import datetime


#funkcija vraca file path na koji se spremaju slike
def upload_location(instance, filename):
    file_path = 'images/blog/{author_id}/{title}-{filename}'.format(
        author_id = str(instance.author.id), title = str(instance.title), filename = filename
    )
    return file_path

class BlogPost(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False)
    body = models.TextField(max_length=5000, null=False, blank=False)
    image = models.ImageField(upload_to=upload_location, null=False, blank=False) 
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    date_updated = models.DateTimeField(auto_now=True, verbose_name="date updated")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='likes')
    dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='dislikes')

    def __str__(self):
        return self.title 
        #vraca naslov kad referenciramo objekt

class Comment(models.Model):
    comment = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null =True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey('BlogPost', on_delete=models.CASCADE)
    
    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if self.id:
            self.updated_at = datetime. datetime. now()
        return super(Comment, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.author} - {self.post}"

#ako se izbrise blog post brise se i slika iz baze ili lokalne mreze/ servera
@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)
#radi slug prije nego je post commited u bazu
def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender = BlogPost) 
 

blog/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import ListAPIView
from rest_framework.filters import SearchFilter, OrderingFilter

from account.models import Account
from blog.models import BlogPost
from blog.api.serializers import BlogPostSerializer

SUCCESS = 'success'
ERROR = 'error'
DELETE_SUCCESS = 'deleted'
UPDATE_SUCCESS = 'updated'


# Url: https://<your-domain>/api/blog/<slug>/
# Headers: Authorization: Token <token>
@api_view(['GET', ])
@permission_classes((IsAuthenticated, ))
def api_detail_blog_view(request, slug):

	try:
		blog_post = BlogPost.objects.get(slug=slug)
	except BlogPost.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	if request.method == 'GET':
		serializer = BlogPostSerializer(blog_post)
		return Response(serializer.data)



# Url: https://<your-domain>/api/blog/<slug>/update
# Headers: Authorization: Token <token>
@api_view(['PUT',])
@permission_classes((IsAuthenticated, ))
def api_update_blog_view(request, slug):

	try:
		blog_post = BlogPost.objects.get(slug=slug)
	except BlogPost.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	user = request.user
	if blog_post.author != user:
		return Response({'response':"You don't have permission to edit that."}) 
		
	if request.method == 'PUT':
		serializer = BlogPostSerializer(blog_post, data=request.data)
		data = {}
		if serializer.is_valid():
			serializer.save()
			data['response'] = UPDATE_SUCCESS
			return Response(data=data)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



# Url: https://<your-domain>/api/blog/<slug>/delete
# Headers: Authorization: Token <token>
@api_view(['DELETE',])
@permission_classes((IsAuthenticated, ))
def api_delete_blog_view(request, slug):

	try:
		blog_post = BlogPost.objects.get(slug=slug)
	except BlogPost.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	user = request.user
	if blog_post.author != user:
		return Response({'response':"You don't have permission to delete that."}) 

	if request.method == 'DELETE':
		operation = blog_post.delete()
		data = {}
		if operation:
			data['response'] = DELETE_SUCCESS
		return Response(data=data)



# Url: https://<your-domain>/api/blog/create
# Headers: Authorization: Token <token>
@api_view(['POST'])
@permission_classes((IsAuthenticated, ))
def api_create_blog_view(request):

	blog_post = BlogPost(author=request.user)

	if request.method == 'POST':
		serializer = BlogPostSerializer(blog_post, data=request.data)
		data = {}
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



# Url: 
#		1) list: https://<your-domain>/api/blog/list
#		2) pagination: http://<your-domain>/api/blog/list?page=2
#		3) search: http://<your-domain>/api/blog/list?search=mitch
#		4) ordering: http://<your-domain>/api/blog/list?ordering=-date_updated
#		4) search + pagination + ordering: <your-domain>/api/blog/list?search=mitch&page=2&ordering=-date_updated
# Headers: Authorization: Token <token>
class ApiBlogListView(ListAPIView):
	queryset = BlogPost.objects.all()
	serializer_class = BlogPostSerializer
	authentication_classes = (TokenAuthentication,)
	permission_classes = (IsAuthenticated,)
	pagination_class = PageNumberPagination
	filter_backends = (SearchFilter, OrderingFilter)
	search_fields = ('title', 'body', 'author__username')

blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Q

from blog.forms import CreateBlogPostForm, UpdateBlogPostForm, CommentForm, EditCommentForm
from account.models import Account
from blog.models import BlogPost, Comment
from django.http import HttpResponse
from django.template import loader
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse

def create_blog_view(request):

    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()
        return redirect("home")
    context['form'] = form
    return render(request, "blog/create_blog.html", context)

def detail_blog_view(request, slug):

    context = {}
    user = request.user
    blog_post = get_object_or_404(BlogPost, slug=slug)
    
    if request.POST:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            obj = comment_form.save(commit=False)
            author = Account.objects.filter(email=user.email).first()
            obj.author = author
            obj.post = blog_post 
            obj.save()
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()
    
    comments = Comment.objects.filter(post=blog_post).order_by('-created_on')
    page = request.GET.get('page')
    results_per_page = 5
    paginator = Paginator(comments, results_per_page)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)
    
    
    context['blog_post'] = blog_post
    context['comment_form'] = comment_form
    context['comments'] = comments

    return render(request, 'blog/detail_blog.html', context)

def edit_blog_view(request, slug):

    context = {}
    user = request.user

    if not user.is_authenticated:
        return redirect("must_authenticate.html")
    
    
    blog_post = get_object_or_404(BlogPost, slug=slug)

    if blog_post.author != user:
        return HttpResponse("You are not the author of this post.")

    if request.POST:
        form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance = blog_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Updated"
            blog_post = obj
    form = UpdateBlogPostForm(
        initial={
            "title": blog_post.title,
            "body": blog_post.body,
            "image": blog_post.image,
        }
    )

    context['form'] = form
    context['slug'] = slug

    return render(request, 'blog/edit_blog.html', context)

def delete_blog_view(request, slug):
    context = {}
    user = request.user

    if not user.is_authenticated:
        return redirect("must_authenticate.html")
    
    
    blog_post = get_object_or_404(BlogPost, slug=slug)

    if blog_post.author != user:
        return HttpResponse("You are not the author of this post.")
    
    if request.method == 'GET':
        context['slug'] = slug
        return render(request, 'blog/delete_blog.html', context)
    
    if request.POST:
        blog_post.delete()

        return redirect('home')
    
   
    blog_post.delete()
    return redirect("home")

def get_blog_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        posts = BlogPost.objects.filter(
            Q(title__icontains = q) | #q serach
            Q(body__icontains = q)
        ).distinct() #gives unique posts in that list

        for post in posts:
            queryset.append(post)
    
    return list(set(queryset))

def edit_commnet_view(request, slug, pk):

    context = {}
    user = request.user

    if not user.is_authenticated:
        return redirect("must_authenticate.html")
    
    comment = Comment.objects.filter(pk=pk)[0]

    if comment.author != user:
        return HttpResponse("You are not the author of this comment.")

    comment_form = CommentForm()
    if request.method == 'GET':
        comment_form = CommentForm(
            initial={
            "comment": comment.comment,
        }
        )
        context['comment_form'] = comment_form
        context['slug'] = slug
        return render(request, 'blog/edit_comment.html', context)
    
    if request.POST:
        comment_form = CommentForm(request.POST or None, request.FILES or None, instance = comment)
        if comment_form.is_valid():
            obj = comment_form.save(commit=False)
            obj.save()
            
    next = request.POST.get('next', '/')
    return redirect(next)

def delete_commnet_view(request, slug, pk):

    context = {}
    user = request.user
    
    if not user.is_authenticated:
        return redirect("must_authenticate.html")
    
    
    comment = Comment.objects.filter(pk=pk)[0]

    if comment.author != user:
        return HttpResponse("You are not the author of this comment.")

    if request.method == 'GET':
        context['slug'] = slug
        return render(request, 'blog/delete_comment.html', context)
    
    if request.POST:
        comment.delete()
        next = request.POST.get('next', '/')

        return redirect(next)

def add_like(request, slug, pk):

    if not request.user.is_authenticated:
        return redirect('must_authenticate')

    if request.POST:
        post = BlogPost.objects.get(pk=pk)

        is_dislike = False

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if is_dislike:
            post.dislikes.remove(request.user)

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if not is_like:
            post.likes.add(request.user)

        if is_like:
            post.likes.remove(request.user)

        next = request.POST.get('next', '/')
        return redirect(next)

def add_dislike(request, slug, pk):

    if not request.user.is_authenticated:
        return redirect('must_authenticate')

    if request.POST:
        post = BlogPost.objects.get(pk=pk)

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if is_like:
            post.likes.remove(request.user)

        is_dislike = False

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if not is_dislike:
            post.dislikes.add(request.user)

        if is_dislike:
            post.dislikes.remove(request.user)

        next = request.POST.get('next', '/')
        return redirect(next)


#

blog/templates/blog/create_blog.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .create-form {
          width: 100%;
          max-width: 100%;
          padding: 15px;
          margin: auto;
        }

    .submit-button{
        max-width: 200px;
    }
</style>
  
  <div class="container">
      <div class="row">
          <div class="col-lg-7 offset-lg-1">
              <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
  
                  <!-- title -->
                  <div class="form-group">
                      <label for="id_title">Title</label>
                      <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
                  </div>
  
                  <!-- Body -->
                  <div class="form-group">
                      <label for="id_body">Content</label>
                      <textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
                  </div>
  
                  <!-- Image -->
                  <div class="form-group ">
                      <label for="id_image">Image</label>
                      <input  type="file" name="image" id="id_image" accept="image/*" required>
                  </div>
  
                  <!-- Submit btn -->
                  
                  <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
              </form>	
          </div>
      </div>
  </div>
  

{% endblock content %}

blog/templates/blog/delete_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<style type="text/css">
	.card{
		max-width: 700px;
	}
	.card-body{
		padding: 20px;
	}
</style>


<div class="card m-auto">
    <div class="card-body mt-2 mb-2">
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-3 col-sm-6">
            <a href="{% url 'blog:detail' slug %}" class="btn btn-light">Back to Post</a>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-8 col-sm-12">
            <h5 style="text-align: center;">Are You Sure?</h5>
            <p>You are about to delete this Blog, this cannot be undone.</p>
        <form method="POST">
            {% csrf_token %}
            <div class="d-grid gap-2">
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        </form>
    </div>
    </div>
</div>
</div>
</div>
{% endblock content %}

blog/templates/blog/delete_comment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<style type="text/css">
	.card{
		max-width: 700px;
	}
	.card-body{
		padding: 20px;
	}
</style>

<div class="card m-auto">
    <div class="card-body mt-2 mb-2">
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-3 col-sm-6">
            <a href="{% url 'blog:detail' slug %}" class="btn btn-light">Back to Post</a>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-8 col-sm-12">
            <h5>Are You Sure?</h5>
            <p>You are about to delete this comment, this cannot be undone.</p>
        <form method="POST">
            {% csrf_token %}
            <div class="d-grid gap-2">
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        </form>
    </div>
    </div>
</div>
</div>
</div>
{% endblock content %}

blog/templates/blog/detail_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<style type="text/css">
	.card{
		max-width: 700px;
	}
	.card-body{
		padding: 20px;
	}
</style>

<div class="container">
	<div class="row">

		<!-- Blog Post -->
		<div class="card m-auto">
			<img class="card-img-top mt-1" src="{{blog_post.image.url}}">
			<div class="card-body mt-2 mb-2">
			  <h2 class="card-title">{{blog_post.title}}</h2>
			  <p class="card-text">{{blog_post.body|safe}}</p>
                {% if blog_post.author == request.user %}
			  	<a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Edit</a>
	            {% endif %}
			</div>
			<form method="POST" action="{% url 'blog:like' blog_post.slug blog_post.pk %}">
				{% csrf_token %}
				<input type="hidden" name="next" value="{{ request.path }}">
				<button style="background-color: transparent; border: none; box-shadow: none;" type="submit">
					<i class="fa fa-thumbs-up" style="color: blue"> <span>{{ blog_post.likes.all.count }}</span></i>
				</button>
			</form>
		
			<form method="POST" action="{% url 'blog:dislike' blog_post.slug blog_post.pk %}">
				{% csrf_token %}
				<input type="hidden" name="next" value="{{ request.path }}">
				<button style="background-color: transparent; border: none; box-shadow: none;" type="submit">
					<i class="fa fa-thumbs-down" style="color: red"> <span>{{ blog_post.dislikes.all.count }}</span></i>
				</button>
			</form>
		
			<div class="card-footer text-muted mb-1">
			  Updated on {{blog_post.date_updated}} by {{blog_post.author}}
			</div>
		</div>
		{% if comments %}
		<div class="card m-auto mt-3" >
			<h3>Comment section:</h3>
		
		<div>{% include 'blog/snippets/comments.html' %}</div>
		<div>{% include 'blog/snippets/comment_pagination.html' %}</div>
		
		</div>
		{% else %}
		<div class="card m-auto mt-3">
			<h3>Comment section:</h3>
			<p>Currently there are no comments on this Post...</p>
		</div>

		{% endif %}
		{% if user.is_authenticated %}
		<div class="card m-auto mt-3">
			
				<form method="POST" style="margin-top: 5px; margin-bottom: 5px;">
					
					{% csrf_token %}
					{{ comment_form | crispy }}
					<div class="d-grid gap-2">
						<button class="btn btn-success mt-3">Submit!</button>
					</div>
				</form>
			
		</div>
		{% endif %}
	</div>
</div>


{% endblock content %}

blog/templates/blog/edit_blog.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
    .create-form {
         width: 100%;
         max-width: 100%;
         padding: 15px;
         margin: auto;
       }
 
       .submit-button{
           max-width: 200px;
       }
 
     .image {
       opacity: 1;
       transition: .5s ease;
       backface-visibility: hidden;
     }
 
     .middle {
       transition: .5s ease;
       opacity: 0;
       position: absolute;
       text-align: center;
       top: 50%;
       left: 50%;
       transform: translate(-50%, -50%);
     
     }
     .image-group{
         position: relative;
           text-align: center;
           cursor:pointer;
     }
 
     .image-group:hover .image {
       opacity: 0.3;
     }
 
     .image-group:hover .middle {
       opacity: 1;
     }
 
     .text {
       margin: auto;
       background-color: #4CAF50;
       color: white;
       font-size: 15px;
       padding: 15px;
     }
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." 
					required>{{form.initial.body}}</textarea>
				</div>

				<!-- Image -->
				<div class="form-group image-group" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
					  <div class="middle">
					    <div class="text">Change image</div>
					  </div>
				</div>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
				<a style="float: right;" href="{% url 'blog:delete-blog' slug %}" class="btn btn-danger">Delete blog</a>
			</form>	
			
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}

blog/templates/blog/edit_comment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<style type="text/css">
	.card{
		max-width: 700px;
	}
	.card-body{
		padding: 20px;
	}
</style>

<div class="container">
	<div class="row">
        <div class="card m-auto mt-3">
        <div class="row justify-content-center mt-3">
            <div class="col-md-3 col-sm-6">
                <a href="{% url 'blog:detail' slug %}" class="btn btn-light">Back to Post</a>
            </div>
        </div>
        {% if user.is_authenticated %}
                
                    
                        <form method="POST"  style="margin-top: 5px; margin-bottom: 5px;">
                            <div style="margin-left: 35px;">
                                {% csrf_token %}
                                {{ comment_form | crispy }}
                            </div>
                            
                            <input type="hidden" name="next" value="{{ request.GET.next }}">
                            <div class="d-grid gap-2">
                                <button class="btn btn-success mt-3">Update!</button>
                            </div>
                        </form>
                    
                
        {% endif %}
    </div>
</div>
</div>
{% endblock content %}